# Generated by Django 5.2.5 on 2025-08-23 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
