# Generated by Django 5.2.5 on 2025-08-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='53e9074f-d6d9-48ed-a9b3-f6bc8ebdb19c', max_length=100, unique=True),
        ),
    ]
