# Generated by Django 5.2.5 on 2025-08-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='4d3f9474-b97a-4fe1-83b2-c5b6bd6e769d', max_length=100, unique=True),
        ),
    ]
