# Generated by Django 5.2.5 on 2025-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='<django.db.models.fields.AutoField>', max_length=100, unique=True),
        ),
    ]
